{% set name = "kedro-mlflow" %}
{% set version = "0.11.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro_mlflow-{{ version }}.tar.gz
  sha256: 777b20e1d5ad6d1bd8520c7aa4a385071667649355578a1af4c46d3345aa3976

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python >=3.7,<3.11
    - setuptools-scm
    - pip
  run:
    - python >=3.7,<3.11
    - kedro >=0.18.1,<0.19.0
    - mlflow >=1.0.0,<3.0.0
    - pydantic >=1.0.0,<2.0.0

test:
  imports:
    - kedro_mlflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Galileo-Galilei/kedro-mlflow
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A Kedro plugin to use mlflow in your Kedro projects
  description: |
    kedro-mlflow is a Kedro plugin for lightweight and portable integration of mlflow capabilities inside kedro projects.
    It enforces Kedro principles to make mlflow usage as production ready as possible. 
    Its core functionalities are versioning and model packaging.
  doc_url: https://kedro-mlflow.readthedocs.io/
  dev_url: https://github.com/Galileo-Galilei/kedro-mlflow

extra:
  recipe-maintainers:
    - Galileo-Galilei
    - rxm7706
